// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env extends Record<string, undefined> {
  /**
   * Whether to proxy all requests.
   * If falsy, redirection to **.hf.co will not be modified.
   */
  PROXY_ALL_HOST: string | undefined;
  /**
   * Whether to use the new XET transfer blobs.
   * If truthy, new versions of transformers/huggingface_hub will follow the Link header and get a long list of blobs.
   * NOTE: This mode consumes significantly more [unnecessary] CPU time.
   */
  USE_XET_TRANSFER: string | undefined;
}
