// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env extends Record<string, undefined> {
  PROXY_ALL_HOST: string | undefined;
}
