name: Unit Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths-ignore: &path-ignore
      - '**.md'
      - '.*'
      - 'LICENSE'
      - '.github/**'
  push:
    paths-ignore: *path-ignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit
